<?php
/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 21.02.2019
 * Time: 10:15
 */

namespace app\components\widgets;


use app\models\Company;
use app\models\Review;
use app\models\XprofileXcompany;
use yii\bootstrap\ActiveForm;
use yii\bootstrap\Html;
use yii\bootstrap\Modal;
use yii\bootstrap\Widget;
use kartik\rating\StarRating;
use yii\helpers\Url;
use yii\web\JsExpression;

class AddCompany extends Widget
{
    public $id_user;
    protected $modelCompany;
    protected $XcompanyXprofile;
    public $redirect;
    public $togggleButton = [
        'label' => 'Добавить...',
        'class' => 'btn btn-primary'
        ];

    public function init(){
        $this->modelCompany = new Company();
        $this->XcompanyXprofile = new XprofileXcompany();
    }

    public function run()
    {
//        parent::run(); // TODO: Change the autogenerated stub
        self::addCompany();
    }

    public function addCompany(){
        Modal::begin([
            'header' => 'Новое юр. лицо',
            'toggleButton' => $this->togggleButton
        ]);

        $form = ActiveForm::begin([
            'action' => Url::to('/company/create', ['user_id' => $this->id_user])
        ]);
        echo $this->render('@app/views/company/_form', [
            'form' => $form,
            'modelCompany' => $this->modelCompany,
            'XcompanyXprofile' => $this->XcompanyXprofile
        ]);
        $form::end();

        Modal::end();
    }
}