<?php
/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 21.02.2019
 * Time: 10:15
 */

namespace app\components\widgets;


use app\models\Review;
use yii\bootstrap\ActiveForm;
use yii\bootstrap\Html;
use yii\bootstrap\Modal;
use yii\bootstrap\Widget;
use kartik\rating\StarRating;
use yii\web\JsExpression;

class AddOrEditReview extends Widget
{
    public $id_user_to;
    public $id_user_from;
    public $message = null;
    public $redirect;
    public $togggleButton = ['label' => 'Оценить', 'class' => 'btn btn-primary'];

    public function run()
    {
//        parent::run(); // TODO: Change the autogenerated stub
        self::review();
    }

    public function review(){
        if($this->message) {
            $reviewModel = Review::find()->where(['id_message' => $this->message->id])->one();
            if(!$reviewModel) {
                $reviewModel = new Review();
                $reviewModel->id_message = $this->message->id;
            } else $this->togggleButton = ['label' => 'Изменить', 'class' => 'btn btn-sm'];
        }
        Modal::begin([
            'header' => 'Отзыв. Заказ №' . $this->message->id_order,
            'toggleButton' => $this->togggleButton
        ]);

        $form = ActiveForm::begin([

        ]);
        echo $form->field($reviewModel, 'value')->widget(StarRating::class, [
            'name' => 'raiting' . $this->message->id,
            'pluginOptions' => [
                'step' => 1,
                'language' => 'ru',
                'filledStar' => Html::img('/img/icons/truck-filled.png'),
                'emptyStar' => Html::img('/img/icons/truck-empty.png'),
                'starCaptions' => [
                    1 => 'Очень плохо',
                    2 => 'Плохо',
                    3 => 'Нормально',
                    4 => 'Хорошо',
                    5 => 'Очень хорошо',
                ]
            ]
        ]);
        echo $form->field($reviewModel, 'comment')->textarea();

        ActiveForm::end();

        Modal::end();
    }
}