<?php
/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 20.04.2018
 * Time: 11:11
 */

namespace app\components\widgets;
use yii\base\Widget;
use yii\bootstrap\ActiveForm;
use yii\bootstrap\Html;
use yii\bootstrap\Modal;
use yii\helpers\Url;
use yii\widgets\DetailView;

class CheckPOA extends Widget
{

    public $model;
    public $return ;

    public function run()
    {
//        parent::run(); // TODO: Change the autogenerated stub
        self::checkPOA();
    }

    public function checkPOA(){
        Modal::begin([
            'header' => 'Проверка и отправка подписанной доверенности',
            'toggleButton' => ['label' => 'Проверить и подписать', 'class' => 'btn btn-success'],
        ]);
//        echo DetailView::widget([
//            'model' => $this->model,
//            'attributes' => [
//                'fio',
//                'company.name',
//                'term_of_office',
//                [
//                    'label' => 'Скачать доверенность',
//                    'attribute' => 'urlsUpload',
//                    'format' => 'raw'
//                ]
//            ]
//
//        ]);
//echo phpinfo();
        $formConfirm = ActiveForm::begin([
            'action' => Url::to(['/poa/confirm-poa', 'id_company' => $this->model->id_company, 'id_user' => $this->model->id_profile, 'return' => $this->return ])
        ]);
        echo Html::submitButton('Подтвердить',['class' => 'btn btn-success']
        );
        ActiveForm::end();

        echo '<br><br>';

        $formError = ActiveForm::begin([
            'action' => Url::to(['/poa/error-poa', 'id_company' => $this->model->id_company, 'id_user' => $this->model->id_profile, 'return' => $this->return ])
        ]);
        echo $formConfirm->field($this->model, 'comments')->textarea();
        echo Html::submitButton('Удалить',['class' => 'btn btn-warning']
        );
        ActiveForm::end();
//
        Modal::end();
    }

}