<?php
/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 26.03.2018
 * Time: 17:19
 */

namespace app\components\widgets;

use yii\base\Widget;
use yii\bootstrap\ActiveForm;
use yii\bootstrap\Html;
use yii\bootstrap\Modal;
use yii\helpers\Url;
use yii\widgets\DetailView;

class CheckDocuments extends Widget
{

    public $model;
    public $typeDocument;



    public function run()
    {
//        parent::run(); // TODO: Change the autogenerated stub
        self::checkContract();
    }

    public function checkContract(){
        Modal::begin([
            'header' => 'Проверка и отправка подписанного договора',
            'toggleButton' => ['label' => 'Проверить и подписать', 'class' => 'btn btn-success'],
        ]);
        echo DetailView::widget([
            'model' => $this->model,
            'attributes' => [
                'id',
                'company.name',
                'date',
                [
                    'label' => 'Скачать договор',
                    'attribute' => 'urlsUpload',
                    'format' => 'raw'
                ]
            ]

        ]);

        $formConfirm = ActiveForm::begin([
            'action' => Url::to(['document/upload-confirm-doc', 'id' => $this->model->id, 'type' => $this->typeDocument ])
        ]);
            echo $formConfirm->field($this->model, 'confirm_file')->fileInput()->label('Выберите файл скана Договора');
            echo Html::submitButton('Загрузить',['class' => 'btn btn-success']
            );

        ActiveForm::end();
echo '<br><br>';
        $formFailed = ActiveForm::begin([
            'action' => Url::to(['document/delete-upload-docs', 'id' => $this->model->id, 'returnRedirectUrl' => '/document/index', 'type' => $this->typeDocument ])
        ]);
        echo $formFailed->field($this->model, 'comments')->textarea();
        echo Html::submitButton('Удалить', ['class' => 'btn btn-warning']);
        ActiveForm::end();

        Modal::end();
    }

    public function checkPowerOfAttorney(){
        Modal::begin([

        ]);



        Modal::end();
    }
}