<?php
/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 17.04.2018
 * Time: 13:28
 */

namespace app\components\widgets;


use yii\base\Widget;
use yii\bootstrap\ActiveForm;
use yii\bootstrap\Html;
use yii\bootstrap\Modal;
use yii\helpers\Url;
use yii\widgets\MaskedInput;

class DownloadPOA extends Widget
{
    public $modelPOA;
    public $modelProfile;
    public $date_end;
    public $return = '/company/index';

    public function init()
    {
//        parent::init(); // TODO: Change the autogenerated stub
        $this->modelProfile = $this->modelPOA->profile;
        $this->date_end = time() + (60*60*24*365);
    }

    public function run()
    {
//        parent::run(); // TODO: Change the autogenerated stub
        self::DownloadPoa();
    }

    public function DownloadPoa(){
        Modal::begin([
            'header' => 'Отредактируйте при необходимости',
            'toggleButton' => ['label' => 'Скачать бланк', 'class' => 'btn btn-success'],
        ]);

        $form = ActiveForm::begin([
            'action' => Url::to([
                '/poa/download-form',
                'id_company' => $this->modelPOA->id_company,
                'id_profile' => $this->modelProfile->id_user,
                'return' => $this->return
            ]),
            'enableAjaxValidation' => true,
            'validationUrl' => \yii\helpers\Url::to(['/company/validate-date']),
        ]);

        echo $form->field($this->modelPOA, 'id')->input('text', [
            'value' => $this->modelProfile->id_user . '-' . $this->modelPOA->id_company,
            'style' => 'width: auto'
        ]);
        echo $form->field($this->modelPOA, 'term_of_office')
            ->widget(MaskedInput::className(),[
                'clientOptions' => [
                ],
                'mask' => '99.99.9999',
                'options' => [
                    'type' => 'tel',
                    'autocorrect' => 'off',
                    'autocomplete' => 'date',
                    'placeholder' => '01.01.2000',
                    'value' => date('d.m.Y', $this->date_end),
                ]
            ])
        ;

        echo Html::submitButton('Скачать', ['class' => 'btn btn-success']);
        echo ' ';
        echo Html::button('Закрыть', ['class' => 'btn btn-warning', 'data-dismiss' => 'modal']);

        ActiveForm::end();

        Modal::end();
    }
}