<?php

/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 19.01.2018
 * Time: 9:12
 */
namespace app\models\signUpClient;
use app\models\Passport;
use app\models\Profile;
use yii\base\Model;
use Yii;
use yii\web\UploadedFile;
use yii\helpers\FileHelper;
use yii\imagine\Image;


class SignUpClientFormStart extends Model
{
    public $bithday;
    public $photo;
    public $passport_number;
    public $passport_date;
    public $passport_place;
    public $email2;
    public $phone2;
    public $country;
    public $reg_address;


    public function rules()
    {
        return [
            ['bithday', 'required'],
//            ['phone2', 'match', 'pattern' => '/^\+7\([0-9]{3}\)[0-9]{3}\-[0-9]{2}\-[0-9]{2}$/'],
            ['phone2',  'string', 'length' => [10], 'message' => 'Некорректный номер', 'tooLong' => 'Некорректный номер','tooShort' => 'Некорректный номер',],
            ['country', 'safe'],
            ['passport_place', 'string', 'length' => [10, 100]],
//            ['passport_number', 'unique', 'targetClass' => 'app\models\Passport', 'targetAttribute' => 'id', 'message' => 'Такой паспорт уже заренистрирован в системе'],
            [['photo'], 'image', 'extensions' => 'jpg'],
            [['passport_number', 'reg_address'], 'string', 'max' => 255],
            ['email2', 'email'],
            [['bithday', 'passport_date'], 'date', 'format' => 'php:d.m.Y'],
        ];
    }

    public function attributeLabels()
    {
        return [
            'bithday' => 'Дата рождения',
            'passport_series' => 'Серия паспорта',
            'passport_number' => 'Номер паспорта',
            'passport_date' => 'Дата выдачи',
            'passport_place' => 'Кем выдан',
            'photo' => 'Фото профиля',
            'phone2' => 'Дополнительный телефон',
            'email2' => 'Дополнительный email',
            'country' => 'Гражданство',
            'reg_address' => 'Адрес регистрации'
        ];
    }
    public function beforeValidate()
    {
        $this->phone2 = mb_ereg_replace("[^0-9]",'',$this->phone2);
        $this->passport_number = mb_ereg_replace("[^0-9]",'',$this->passport_number);
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }


    public function uploadPhoto(){
        if($this->validate() && $this->photo){
            $dir = Yii::getAlias('@userPhotoDir').'/';
            $filename = Yii::$app->user->getId() . '.' . $this->photo->extension;
            $this->photo->saveAs($dir.$filename);
            Image::thumbnail($dir.$filename, 768, null)->save();
            return $filename;
        }else{
            return null;

        }
    }


    public function saveProfile()
    {
        $modelProfile = new Profile();
        $modelProfile = Yii::$app->user->identity->profile;
        $this->photo = UploadedFile::getInstance($this, 'photo');
        if($this->photo) {
            $modelProfile->photo = $this->uploadPhoto();
        }
        $modelProfile->phone2 = $this->phone2;
        $modelProfile->email2 = $this->email2;
        $modelProfile->bithday = ($this->bithday);
        $modelProfile->reg_address = $this->reg_address;

        if($modelProfile->save()) {
            $auth = Yii::$app->authManager;
            $role = $auth->getRole('client');
            $auth->revokeAll($modelProfile->id_user);
            $auth->assign($role, $modelProfile->id_user);
            $modelPassport = $this->addPassport();
            if($modelPassport) {
                $modelProfile->id_passport = $modelPassport->id;
                if($modelProfile->save()) {
                    return $modelProfile;
                }
            }
        }
//        return $modelProfile;
        return false;
    }
    public function addPassport()
    {

        $modelPassport = new Passport();
        $modelPassport->number = $this->passport_number;
        $modelPassport->date = $this->passport_date;
        $modelPassport->place = $this->passport_place;
        $modelPassport->country = $this->country;
        if ($modelPassport->save()) {
            return $modelPassport;
        }
        return false;
    }


}

