<?php

namespace app\controllers;

use app\components\ApiComponent;
use Yii;
use app\models\Profile;
use app\models\User;
use yii\helpers\Json;
use yii\rest\ActiveController;
use yii\web\Response;

class ApiController extends ApiComponent
{
    public $modelClass = User::class;

public function beforeAction($action)
{
    if($action->id == 'login'){
        $this->detachBehavior('authenticator');
    }
    return parent::beforeAction($action); // TODO: Change the autogenerated stub
}

    public function actionViewer(){
        return (Profile::findOne(['id_user' => '1']));
    }

    public function actionLogin(){
//        Yii::$app->response->format = Response::FORMAT_JSON;
        $request = Yii::$app->request->getBodyParams();
        $username = $request['phone'];
        $password = $request['password'];

        if($username){
            $User = User::findOne(['username' => $username]);
            if($User){
                if($User->validatePassword($password)){
                    $return = [
                        'status' => 'OK'
                    ];

                    $return['userid'] = $User->id;
                    $return['roles'] = $User->getRolesString();
                    $return['token'] = $User->auth_key;
                    return $return;
                }
            }
        }

        return [
            'status' => 'ERROR'
        ];

    }



}
