<?php

namespace app\models;

use app\components\functions\functions;
use Yii;
use app\components\DateBehaviors;
use app\models\setting\Setting;
use nickcv\encrypter\behaviors\EncryptionBehavior;
/**
 * This is the model class for table "drivers".
 *
 * @property integer $id
 * @property integer $id_car_owner
 * @property string $name
 * @property string $surname
 * @property string $patronymic
 * @property integer $birthday
 * @property string $address
 * @property integer $passport_id
 * @property integer $license_id
 * @property string $phone
 * @property string $phone2
 * @property integer $raiting
 * @property integer $checking
 * @property integer $create_at
 * @property string $fio
 * @property string $photo
 * @property Passport $passport
 * @property DriverLicense $license
 * @property integer $status
 * @property string $statusString
 * @property string $fullInfo
 */
class Driver extends \yii\db\ActiveRecord
{

    const STATUS_DELETED = 0;
    const STATUS_ACTIVE = 1;
    const STATUS_ARHIVE = 2;


    public $statuses = [
        'Удален',
        'Активен'
    ];
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'drivers';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'surname', 'phone', 'address', 'birthday'], 'required'],
            [['passport_id', 'license_id', 'raiting', 'checking'], 'integer'],
            ['birthday', 'date' , 'format' => 'php:d.m.Y'],
            [['address'], 'string'],
            [['phone', 'phone2'], 'string', 'max' => 16],
            [['name', 'surname', 'patronymic'], 'string', 'max' => 32],
            ['checking', 'default', 'value' => 0],
            ['create_at', 'default', 'value' => date('d.m.Y')],
            ['photo', 'default', 'value' =>  Setting::getNoPhotoPath()],
            ['status', 'default', 'value' => self::STATUS_ACTIVE],
            ['id_car_owner', 'integer']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Имя',
            'surname' => 'Фамилия',
            'patronymic' => 'Отчество',
            'birthday' => 'Дата рождения',
            'address' => 'Адрес регистрации',
            'passport_id' => 'Passport ID',
            'license_id' => 'License ID',
            'phone' => 'Номер телефона',
            'phone2' => 'Дополнительный номкр телефона',
            'raiting' => 'Рейтинг',
            'checking' => 'Проверен',
            'create_at' => 'Дата создания',
            'fio' => 'ФИО',
            'status' => 'Статус'
        ];
    }

    public function behaviors()
    {
        return [
            'encryption' => [
                'class' => '\nickcv\encrypter\behaviors\EncryptionBehavior',
                'attributes' => [
                    'address',
                ],
            ],
            'convertDate' => [
                'class' => 'app\components\DateBehaviors',
                'dateAttributes' => ['birthday', 'create_at'],
                'format' => DateBehaviors::FORMAT_DATE,
            ]
        ];
    }

    public function beforeDelete()
    {
        $this->deletePhoto();
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function getPassport(){
        return $this->hasOne(Passport::className(), ['id'=>'passport_id']);
    }

    public function getLicense(){
        return $this->hasOne(DriverLicense::className(), ['id' => 'license_id']);
    }

    public function getFio(){
        return $this->surname. ' '. $this->name. ' '. $this->patronymic;
    }

    public function setStatus($status){
        if($this->status!=$status){
            $this->status = $status;
            return ($this->save()) ? true : false;
        }
        return false;
    }

    public function getStatusString(){
        switch ($this->status){
            case 0:
                return 'Удален';
            case 1:
                return 'Активен';
            default:
                return 'Не установлен';
        }
    }

    public function getFullInfo($showPhone = false, $showPassport = false, $showDriveLicense = false){
        $return = $this->fio . '<br>';
        if($showPhone) {
            $return .= 'Телефон: ' . functions::getHtmlLinkToPhone($this->phone);
            if ($this->phone2) $return .= ' (доп. ' . functions::getHtmlLinkToPhone($this->phone2) . ')';
            $return .= '. <br>';
        }
        if($showPassport) $return .= 'Пасспорт: ' . $this->passport->fullInfo . ' <br>';
        if($showDriveLicense) $return .= 'ВУ: ' . $this->license->fullInfo . ' <br>';

        return $return;
    }

    public function deletePhoto(){
        $file = $this->getPhotoFullPath();
        if(file_exists($file && is_file($file))) {
            if(unlink($file)){
                $this->photo = Setting::find()->one()->noPhotoPath;
                return true;
            }
            return false;
        }
        $this->photo = Setting::find()->one()->noPhotoPath;
        return true;

    }

    public function getPhotoFullPath(){
        return Yii::getAlias('@driverPhotoDir/').$this->photo;
    }

}
