<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "message".
 *
 * @property int $id
 * @property int $type
 * @property string $title
 * @property string $text
 * @property int $status
 * @property int $id_to_user
 * @property int $id_from_user
 * @property int $email_status
 * @property int $sms_status
 * @property int $push_status
 */
class Message extends \yii\db\ActiveRecord
{
    const STATUS_NEED_TO_SEND = 1;
    const STATUS_SEND = 2;

    private $idPushall = "4781";

    private $keyPushall = "fbbc4ea3fbe1cdb2f7fc1b4246d48174";
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'message';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['type', 'status', 'id_to_user', 'id_from_user', 'email_status', 'sms_status', 'push_status'], 'integer'],
            [['id_to_user'], 'required'],
            [['title', 'text'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'type' => 'Type',
            'title' => 'Title',
            'text' => 'Text',
            'status' => 'Status',
            'id_to_user' => 'Id To User',
            'id_from_user' => 'Id From User',
            'email_status' => 'Email Status',
            'sms_status' => 'Sms Status',
            'push_status' => 'Push Status',
        ];
    }

    public function afterSave($insert, $changedAttributes)
    {
        if($this->push_status == self::STATUS_NEED_TO_SEND){
            $this->sendPush();
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public function sendPush(){

        if($push_ids = User::findOne($this->id_to_user)->push_ids) {
            foreach ($push_ids as $push_id) {

                $url = Yii::$app->urlManager->createAbsoluteUrl([

                    'https://pushall.ru/api.php',

                    'type' => 'unicast',

                    'id' => $this->idPushall,

                    'key' => $this->keyPushall,

                    'uid' => $push_id,

                    'title' => $this->title,

                    'text' => $this->text,

                    'url' => 'http://2.grigorov.org/order/vehicle',

                    'priority' => '1'

                ], 'https');

                file_get_contents($url);
                $this->push_status = self::STATUS_SEND;
                $this -> save();
                return var_dump($this->getErrors());
            }
        }
    }
}
