<?php

namespace app\models;

use Yii;
use kartik\rating\StarRating;
use app\components\DateBehaviors;

/**
 * This is the model class for table "review".
 *
 * @property int $id
 * @property int $value
 * @property int $id_user_from
 * @property int $id_user_to
 * @property string $comment
 * @property int $type
 * @property int $status
 * @property int $create_at
 * @property int $update_at
 * @property int $id_message
 * @property int $id_order
 * @property int $event

 */
class Review extends \yii\db\ActiveRecord
{
    const TYPE_TO_VEHICLE = 1;
    const TYPE_TO_CLIENT = 2;

    const STATUS_DELETED = 0;
    const STATUS_ACTIVE = 1;
    const STATUS_ONCHECKING = 2;

    const EVENT_NULL = 0;
    const EVENT_ORDER_COMPLETED = 1;
    const EVENT_RE_ORDERING = 2;
    const EVENT_ORDER_CANCELED = 3;
    const EVENT_INVOICE_PAID_ON_TIME = 4;
    const EVENT_INVOICE_PAID_NOT_TIME = 5;
    const EVENT_CERTIFICATION_SIGNED_ON_TIME = 6;
    const EVENT_EVENT_CERTIFICATION_SIGNED_NOT_TIME = 7;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'review';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['value', 'id_user_from', 'id_user_to', 'type'], 'required'],
            [['value', 'id_user_from', 'id_user_to', 'type', 'status', 'id_message', 'id_order'], 'integer'],
            [['comment'], 'string'],
            [['create_at', 'update_at'], 'default', 'value' => date('d.m.Y H:i')],
            ['status', 'default', 'value' => self::STATUS_ONCHECKING],
            ['event', 'default', 'value' => self::EVENT_NULL]
        ];
    }
    public function behaviors()
    {
        return [
            'convertDateTime' => [
                'class' => 'app\components\DateBehaviors',
                'dateAttributes' => ['create_at', 'update_at'],
                'format' => DateBehaviors::FORMAT_DATETIME,
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'value' => 'Оценка',
            'id_user_from' => 'Id User From',
            'id_user_to' => 'Id User To',
            'comment' => 'Комментарий (не обязательно)',
            'type' => 'Type',
            'status' => 'Status',
            'create_at' => 'Create At',
            'update_at' => 'Update At',
        ];
    }

    public function beforeSave($insert)
    {
        if(!$insert){
            $this->update_at = date('d.m.Y H:i');
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function getRatingImage(){
        if($this->value){
            return StarRating::widget([
                'name' => 'raiting'.$this->id,
                'value' => $this->value,
                'pluginOptions' => [
                    'filledStar' => '<i class="glyphicon glyphicon-star" style="color: #821e82"></i>',
                    'emptyStar' => '<i class="glyphicon glyphicon-star"></i>',
                    'readonly' => true,
                    'starCaptions' => [
                        1 => 'Очень плохо',
                        2 => 'Плохо',
                        3 => 'Нормально',
                        4 => 'Хорошо',
                        5 => 'Очень хорошо',
                    ],
                    'showClear' => false,
                    'size' => 'xm',
                    'showCaption' => false
                ]
            ]);
        }
        return false;
    }
}
